id = "nightfox_m"
name = "nightfox_m"
version = "0.0.1"
schema_version = 1
authors = [
    "Mladen Popadić <mladen.popadic.4@gmail.com>",
]
description = "Mladen's custom nightox theme"
repository = "https://github.com/mpopadic/nightfox_m-zed"
