id = "nightfox-m"
name = "Night-M"
version = "0.2.0"
schema_version = 1
authors = [
    "Mladen Popadić <mladen.popadic.4@gmail.com>",
]
description = "Mladen's custom themes"
repository = "https://github.com/mpopadic/nightfox_m-zed"
